### PR TITLE
Update overwolf-social-twitter.md

### PR DESCRIPTION
**Pull request by Colorfulstan**

### CODE REVIEW

**Comment by Colorfulstan** [comment]
@eransharv then it's bugged, I just tried it yesterday and it doesn't work with an array, only with a single object

**Comment by Colorfulstan** [comment]
```overwolf.social.twitter.share(
{
    file: `C:\\Users\\Jay\\Videos\\Overwolf\\LoLwiz\\CLASSIC\\CLASSIC_11-14-2019_22-07-09-674\\CLASSIC 11-14-2019 22-12-40-651.mp4`, 
    message: "some cool shit #something", 
    trimming: {startTime: 0, endTime: 3000
}}, console.log)```

**Comment by Colorfulstan** [comment]
it's also the `trimming` property I changed, if there is another one `segments` that you refered to then that's not documented

**Comment by Colorfulstan** [comment]
Just tried it, and `segments` doesn't do anything, while trimming does not accept an array (even when trying to stringify it)

image

**Comment by eransharv** [comment]
@Colorfulstan, you are right. thanks. merging.

**Pull request merged**
