### PR TITLE
Overwolf game events documentation for MakerKing

### PR DESCRIPTION
**Pull request by WinterAlexander**
Hello there,

I am the developer of MakerKing and I've been given the task of filling up the documentation for the events of my game. However, I am not very familiar with Overwolf app development and I am quite unsure about how things should be.

The full list of events can be seen here: https://gist.github.com/WinterAlexander/8c18aa88b6d145ff530c6e4efd60f42e

I have cut down that list of events into 3 features (level, user, race) trying to match how it works on the documentation of other games. (e.g. PUBG)  Each features has its list of events with data. However it is hard for me to predict the exact JSON of the output the Overwolf app will receive. The JSON the game outputs seems to be relatively different from the standard I observe in other games (see link above to see the format MakerKing output). This leads me to believe some amount of processing of the JSON will happen by Overwolf. In this case I cannot really specify what will be the example JSON in this documentation page.

In any case I'd love to have pointers on how to proceed from here. I did my best filling up this documentation page and documenting each event.

Best,
Winter

### CODE REVIEW

**Comment by eransharv** [comment]
hey @WinterAlexander,
Sorry for the delay, I'm not in the office for the last few days. 
I merged your pull request as anyway this page is not in the menu (so people without a direct link can't access it).
Hopefully, I'll be back to work tomorrow, but I'll check the page tomorrow.

Thanks.

**Comment by WinterAlexander** [comment]
Hey @eransharv I hope you had great holidays! Do you have any time to check it now?

**Comment by eransharv** [comment]
@WinterAlexander, hey. We are on it, and we will inform you ASAP (this week).

**Comment by eransharv** [comment]
@WinterAlexander, as these game events are quite different from the other game events, we decided to clone YOUR documentation and copy-paste it from your git readme. Please review it and edit it add the necessary info if missing.
In case that you need anything from us, please tell me. 
In addition, we added the page to the left menu, and now it is public.

**Pull request merged**
