### PR TITLE
fixed pseudo_match_id description to say it's the match id, not sessi…

### PR DESCRIPTION
**Pull request by Sorikairox**
…on :P

### CODE REVIEW

**Comment by eransharv** [comment]
@Sorikairox, thanks for the editing! before merging, I want to double-check it with the R&D to make sure that it's not intended.

**Comment by Sorikairox** [comment]
@eransharv Sure. If it's intented then the attribute name is misleading ^^

**Comment by eransharv** [comment]
@Sorikairox, so I will accept this PR as your description is better than the current. We called it session id, as we want to emphasize that it's a unique match ID that Overwolf generates. But this name is a little bit misleading, so we accept your suggestion. Thanks!

**Comment by Sorikairox** [comment]
@eransharv My change was motivated by the fact that "sessionID" actually exist in the "running game" object ^^

**Pull request merged**
